### ISSUE TITLE
Consider setting net.Dialer.KeepAlive or http.Transport.IdleConnTimeout greater than zero

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry/cfhttp#4]
Problem statement:

Our corporate infrastructure makes heavy use of physical firewall devices which by default are configured to drop connections after a period of inactivity (30 minutes). Diego components use persistent connections to talk to each other. After prolonged platform inactivity we see errors resulting from connections being severed by our firewall.

Solution

I can think of 2 possible solutions:
1. set net.Dialer.KeepAlive greater than zero
2. set  http.Transport.IdleConnTimeout greater than zero

**Comment by yatzek** [comment]
Ideally both KeepAlive and IdleConnTimeout should be like in http.DefaultTransport:

var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}).DialContext,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}

**Comment by emalm** [comment]
Hi, @yatzek,

We've set the `IdleConnTimeout` to 90 seconds on the `http.Transport` that the cfhttp package creates, to match the default value in Golang 1.8. That change is also available in Diego [v1.26.0](https://github.com/cloudfoundry/diego-release/releases/tag/v1.26.0), so I'm closing out this issue. If you see any additional problems, please feel free to create a new issue here or on the diego-release repository.

Best,
Eric, CF Diego PM
