### ISSUE TITLE
user can customize dial timeout

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cfhttp#5]
I am using cfhttp in my application and it tries to connect to cloudfoundry cloud controller. Now I got the error below when deploy my application to bosh-lite. How about make user can set the value of dial timeout instead of hardcoded it to 5s?

{"data":{"API":"https://api.bosh-lite.com","error":"Get https://api.bosh-lite.com/v2/info: dial tcp: i/o timeout"},"log_level":2,"log_time":"2018-10-18T03:15:37Z","message":"scalingengine.failed to login cloud foundry","source":"scalingengine","timestamp":"1539832537.023622990"}

**Comment by emalm** [comment]
Thanks for filing this issue, @qibobo. The Diego team had a chance to review the public interface to the cfhttp package last week, and we plan to make some breaking changes to it that would allow this dial timeout to be configured. We expect to get to this work in a few weeks.

Best,
Eric, CF Diego PM

**Comment by sunjayBhatia** [comment]
@qibobo the `v2` package support the usage of multiple options in a more generic constructor, for example:

```
cfhttpv2.New(cfhttpv2.WithDialTimeout(10 * time.Second))
```
We would like to start moving users over to the `v2` package as we think this is more maintainable and a better pattern to stick with

Let us know if you need any more help or clarification in this issue, I will close it for now
