### ISSUE TITLE
Support more cipher suites?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cfhttp#6]
The supported cipher suites are only the two ones below when call NewTLSConfig function. Is there any special consideration? Why not to use golang default cipher suites?

var SUPPORTED_CIPHER_SUITES = []uint16{
	tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
}

**Comment by qibobo** [comment]
@jvshahid In our repo(https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/src/autoscaler/helpers/httpclient.go) we use cfhttp as http client to do tls communication. And there are some components which is not written in golang. So we wonder if cfhttp can support more cipher suites.

**Comment by jvshahid** [comment]
You need to provide more information.  What is the other component you are trying to communicate with ? or what language that component is written in ?  Furthermore, what cipher suites does it support ?  Having the list of supported cipher suites will make it easier to decide whether those are strong enough for inclusion in cfhttp

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.
